name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      name: Deploy using deployctl
      uses: denoland/deployctl@v1
      with:
        project: bookshelf
        entrypoint: index.html
        root: build
