name: vercel-deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy-main:
    runs-on: ubuntu-latest
    name: Deploy main
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.ORG_ID }} #Required
      VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }} #Required

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.13.2"
      - run: npm install
      - run: npx vercel pull --yes --token ${VERCEL_TOKEN}

      - run: npx vercel  --token ${VERCEL_TOKEN} build
      - name: Deploy main to Vercel
        run: npx vercel --token ${VERCEL_TOKEN} --prebuilt
